"""empty message

Revision ID: 210f97314345
Revises: b01856b008b6
Create Date: 2023-04-28 03:26:01.413257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210f97314345'
down_revision = 'b01856b008b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=True),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('task_based', 'another', name='contestformat'), nullable=True),
    sa.Column('feeding', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('individual', 'command', name='contesttype'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('employer', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    op.drop_table('invite')
    op.drop_table('contest')
    # ### end Alembic commands ###
